sudo: required

language: ruby
cache: bundler

env:
  global:
  - MYSQL_PORT=3306

services:
  - mysql

before_install:
  - mysql --verbose --user=root --host=127.0.0.1 --port=3306 mysql < spec/config/bootstrap.sql

script:
  - bundle exec rake spec
