test: &test
  adapter: mysql2
  username: root
  password:
  host: localhost
  encoding: utf8
  read_timeout: 1
  database: test_db

readonly_login: &readonly_login
  <<: *test
  username: read_only
  password: readme

test_pool_secondary_name_db1:
  <<: *readonly_login

test_pool_secondary_name_db2:
  <<: *readonly_login

test_pool_secondary_name_db3:
  <<: *readonly_login

test_pool_default_name_db1:
  <<: *readonly_login

test_pool_default_name_db2:
  <<: *readonly_login
